name: my first wf

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v5
            - name: List and read files
              run: |
                   echo "first gha jab"
                   ls -ltra
                   cat README.md
            - name: Generate ascii
              run: cowsay -f dragon " Run for cover" >> drag.txt