name: generate ascii

on: 
 push

jobs: 
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v5
            - name: run script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh
